### ISSUE TITLE
Review DAO revamp requirement to give estimation

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#170]
## Background
We'll start to work on DAO revamp after 22 Apr, before that need to plan for it

## Todo
- [x]  Review DAO revamp requirement and design
- [x] Fill in the estimation in master requirement (Please note the whole site supports RWD)
- [x] Write down implementation notes if find anything helpful or having a rough plan
- [x] Find corresponding API query

## Reference
- Basecamp thread: [📢 Kick off of dao.like.co design project](https://3.basecamp.com/3096882/buckets/25656427/messages/4680912993)
- Figma design: https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=55%3A485
- Master requirement: https://docs.google.com/spreadsheets/d/1DvAM2KP4uW3D4abioFhXdY00m30IxwZQS5WvSihP25c/edit?usp=sharing

**Comment by hochiw** [comment]
I assume we are using React for this one

**Comment by hochiw** [comment]
@mitchellchou may i get edit access? thanks

**Comment by mitchellchou** [comment]
@chihimng I just added items 1.1 & 1.2 & 2.2 to the master requirement.
Could you see if they are correct? And if they have extra work to do, could you also put on the estimation?

I thinks to switch between mainnet and testnet, our UI should be revised too?

Thanks
