### ISSUE TITLE
[NFT] Claim / Pay to mint

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#192]
Ref https://www.notion.so/oursky/NFT-Pay-To-Mint-Drop-Flow-Research-f97a822418f24b4088bf4cb98dfdc01e for background research

## Proposed user flow
1. Creator set following in class metadata:
    1. metadata of class (collection)
    2. metadata of all tokens
    3. claim stages
        1. time + approved users / allow for all + price
    4. reveal time
2. Users pay-to-mint for sealed tokens
    1. Check permission in claim stages
3. At reveal time, chain will reveal all tokens:
    1. Unclaimed tokens will be minted and assigned to class owner
        1. creators can offer to sale at marketplace
    2. Update metadata for all tokens
        1. Token to metadata mapping shuffled with last block app hash as seed
        2. Call `UpdateNFT` to write metadata
            1. Note ibc concern here, might be frozen if token is off chain - need to check finalized spec

## Proposed Implementation details
- Obtain real-world time:
    - ctx.BlockHeader().Time
- Reveal scheduling:
    - Mostly based on x/gov proposal queue processing
    - Keep a queue of nft classes to be revealed, key by reveal timestamp + class id
    - At endblocker, iterate and process queue up to ctx.BlockHeader().Time
- Random:
    - Use math/rand: seed with ~~ctx.BlockHeader().LastBlockId.Hash~~ ctx.BlockHeader().AppHash (for block 1, last block is empty, use app hash instead)

## TODO
- [ ] Refactor NFTInput from MsgMintNFT, Keep array of NFTInput in ClassData
- [ ] Implement claim stages: Keep schedule in ClassData, Check permission at claim
- [ ] Add flag in NFTData to reflect sealed status & expected reveal time
- [ ] Implement reveal queue and processing: Keep reveal time at ClassData, Update queued entry on change, Process queue at endblocker
- [ ] Implement reveal business logic

**Comment by chihimng** [comment]
might want to refactor claim from mint? cc @Rico-Wong any opinion?

**Comment by mitchellchou** [comment]
@rickmak pls review for us~

**Comment by rickmak** [comment]
I think we need to add the gas/payment consideration here?

I think for Creator it should pay a fee based on: 1. storage, one off platform fee.

So likenft should have two config, price per byte, price per nft?
