### ISSUE TITLE
[NFT] Tests for claimable nfts

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#223]
Ref oursky/likecoin-chain#192 , oursky/likecoin-chain#202 

## Already done:
- unit test for keeper method to access claimables store
- unit test for grpc / cli query

## TODO:
- [x] msg server unit tests
- [ ] e2e test for claimable user flow
- [x] claimable count unit tests

## Checklist:
- [x] msg server create mintable (new)
- [x] msg server delete mintable (new)
- [x] msg server update mintable (new)
- [x] e2e account blindbox (new)
- [ ] e2e iscn blindbox (new)
- [x] msg server burn nft (recheck)
- [x] msg server mint nft (recheck)
- [x] msg server new class (recheck)
- [x] msg server update class (recheck)
- [ ] e2e account normal (recheck)
- [ ] e2e iscn normal (recheck)

**Comment by chihimng** [comment]
need to review everything and make a checklist
